import CIPHER_VAULT_ABI_JSON from './json/CIPHER_VAULT_ABI.json'

export const CIPHER_VAULT_ABI = CIPHER_VAULT_ABI_JSON
export const CIPHER_VAULT_ADDRESS = "0xEF5a0f3F1e6924F3Fb5160C3e0A4DB3ed3B5DEEb"